# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_stages: [commit]
minimum_pre_commit_version: 3.0.0

repos:

# Enable a whole bunch of useful helper hooks.
# See https://pre-commit.com/hooks.html for more hooks.
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: end-of-file-fixer
    stages: [commit]
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    stages: [commit]
  - id: detect-private-key
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: check-yaml

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: text-unicode-replacement-char

# Check and prettify the configuration files.
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]

# Check GitHub Actions workflow files.
- repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  rev: v1.6.25.9
  hooks:
  - id: actionlint
