name: Pull Request Status Auto-merge
on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write

env:
  USER_NAME: davikawasaki
  USER_EMAIL: davishinjik@gmail.com

jobs:
  trigger-on-approval:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
    - name: Debug status
      env:
        STATE: ${{ github.event.review.state }}
      run: |
        echo "Event state: $STATE"
        echo ${{ toJson(github) }}
    - name: Auto-merge with --ff-only
      env:
        GH_TOKEN: ${{ secrets.CI_TOKEN }}
      run: |
        git config --global user.name "$USER_NAME"
        git config --global user.email "$USER_EMAIL"
        # git merge --ff-only origin/uat
