name: Pull Request Status Auto-merge
on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

env:
  USER_NAME: davikawasaki
  USER_EMAIL: davishinjik@gmail.com

jobs:
  trigger-on-approval:
    uses: ./.github/workflows/_automerge.yaml
    with:
      pull_request_review_state: ${{ github.event.review.state }}
      pull_request_head_branch: ${{ github.event.pull_request.head.ref }}
      pull_request_base_branch: ${{ github.event.pull_request.base.ref }}
      pull_request_title: ${{ github.event.pull_request.title }}
      pull_request_number: ${{ github.event.pull_request.number }}
      pull_request_full_organization_repo_name: ${{ github.repository }}
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
