name: Pull Request Status Auto-merge

on:
  check_suite:
    types: [completed]

permissions:
  contents: read

jobs:
  trigger-on-check-success:
    runs-on: ubuntu-latest
    steps:
    - name: Check
      uses: arup-group/action-all-checks-passed@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Debug
      run: |
        echo "Success checks "
